# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GroundWorks' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  	pod 'AWSMobileClient', '~> 2.6.13'
	pod 'AWSAuthCore', '~> 2.6.13'
      	pod 'AWSAPIGateway', '~> 2.6.13'
	pod 'AWSLambda'
  # Pods for GroundWorks

end
